---
- hosts: localhost
  tasks:
  - name: Get facts by name
    azure_rm_networkinterface_facts:
      resource_group: "{{ rg }}"
      name: tsthd0
    register: niec_facts

  - debug:
      var: niec_facts
