- hosts: localhost
  tasks:
    - name: get_vm_facts
      setup:
      delegate_facts: True
      delegate_to: "{{ vm_name }}"
      register: azure_vm_facts

    - name: Getting instance id
      set_fact: 
        vm_id: "{{ azure_vm_facts.ansible_facts.ansible_machine_id }}"

    #- name: Getting existing block devices
    #  set_fact:
    #    block_devices: "{{ azure_vm_facts.ansible_facts.ansible_devices.split(',')}}"


    - name: test
      azure_rm_managed_disk:
        resource_group: "{{ rg }}"
        name: "{{ disk_name }}"
        disk_size_gb: "{{ disk_size }}"
        storage_account_type: Standard_LRS
        managed_by: "{{ vm_name }}"
