- hosts: localhost
  tasks:
    - name: add a private ip
      azure_rm_networkinterface:
        resource_group: "{{ rg }}"
        virtual_network: "{{ vnet }}"
        subnet_name: "{{ vnet_subnet }}"        
        name: poctest111
        ip_configurations:
          - name: ipconfig2
            primary: false
