- name: Generate /etc/ssh/ RSA host key
  command : ssh-keygen -q -t rsa -f {{ ssh_key_path }}/{{ key_name }} -C "" -N ""
- name: az login
  command: az login --service-principal --username  {{ principal_name }} --password {{ principal_password }}  --tenant {{ principal_tenant }}
    
- name: upload private key
  command: az keyvault secret set --name {{ key_name }}-private --vault-name {{ keys_vault }} --file ~/.ssh/ansible-keys/{{ key_name }}

- name: upload public key
  command: az keyvault secret set --name {{ key_name }}-public --vault-name {{ keys_vault }} --file ~/.ssh/ansible-keys/{{ key_name }}.pub

