- name: Create Virtual Network Interface Card
  azure_rm_networkinterface:
    resource_group: "{{ rg }}"
    name: "{{ network_interface_name }}"
    virtual_network: "{{ vnet }}"
    subnet: "{{ vnet_subnet }}"
    security_group: "{{ sec_ng }}"
    ip_configurations:
      - name: primary
        primary: true
        public_ip_address_name: "{{ vm_name }}"
